"""Hero definitions - Hearthstone Battlegrounds"""

HEROES = {
    57944: {
        "name": "A. F. Kay",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 59891,
            "name": "Procrastinate",
            "cost": 0,
            "text": "Skip your first two turns, then <b>Discover</b> a minion from Tier 3 and Tier 4.",
        },
        "buddy": {
            "id": 77774,
            "name": "Snack Vendor",
            "attack": 6,
            "attackGold": 12,
            "health": 6,
            "healthGold": 12,
            "text": "At the end of your turn, give this minion's stats to a Tier 3 minion.",
            "textGold": "At the end of your turn, give this minion's stats to a Tier 3 minion twice.",
        },
    },
    64403: {
        "name": "Al'Akir",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 64402,
            "name": "Swatting Insects",
            "cost": 0,
            "text": "<b>Start of Combat:</b> Give your left-most minion <b>Windfury</b>, <b>Divine Shield</b>, and <b>Taunt</b>.",
        },
        "buddy": {
            "id": 77447,
            "name": "Spirit of Air",
            "attack": 5,
            "attackGold": 10,
            "health": 2,
            "healthGold": 4,
            "text": "<b>Deathrattle:</b> Give a random friendly minion <b>Windfury</b>, <b>Divine Shield</b>, and <b>Taunt</b>.",
            "textGold": "<b>Deathrattle:</b> Give 2 random friendly minions <b>Windfury</b>, <b>Divine Shield</b>, and <b>Taunt</b>.",
        },
    },
    61488: {
        "name": "Alexstrasza",
        "health": 30,
        "armor": 10,
        "power": {
            "id": 61517,
            "name": "Queen of Dragons",
            "cost": 1,
            "text": "<b>Discover</b> a Dragon. <i>(Unlocks at Tier 4.)</i>",
        },
        "buddy": {
            "id": 77448,
            "name": "Vaelastrasz",
            "attack": 6,
            "attackGold": 12,
            "health": 6,
            "healthGold": 12,
            "text": "<b>Rally:</b> Get a random Dragon.",
            "textGold": "<b>Rally:</b> Get 2 random Dragons.",
        },
    },
    81569: {
        "name": "Ambassador Faelin",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 81570,
            "name": "Expedition Plans",
            "cost": 0,
            "text": "Skip your first turn. <b>Discover</b> minions from Tiers 6, 4, and 2 to get at those Tiers.",
        },
        "buddy": {
            "id": 82604,
            "name": "Submersible Chef",
            "attack": 4,
            "attackGold": 8,
            "health": 3,
            "healthGold": 6,
            "text": "<b>Battlecry:</b> Get a random minion each from Tiers 1, 3, and 5.",
            "textGold": "<b>Battlecry:</b> Get two random minions each from Tiers 1, 3, and 5.",
        },
    },
    61910: {
        "name": "Aranna Starseeker",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 61915,
            "name": "Demon Hunter Training",
            "cost": 0,
            "text": "After 14 friendly minions attack, the first minion you buy each turn is free. <i>(14 left!)</i>",
        },
    },
    60362: {
        "name": "Arch-Villain Rafaam",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 60381,
            "name": "I'll Take That!",
            "cost": 1,
            "text": "Next combat, get a plain copy of the first minion you kill.",
        },
        "buddy": {
            "id": 77470,
            "name": "Loyal Henchman",
            "attack": 4,
            "attackGold": 8,
            "health": 6,
            "healthGold": 12,
            "text": "After you kill a second minion each combat, get a plain copy of it.",
            "textGold": "After you kill a second minion each combat, get 2 plain copies of it.",
        },
    },
    118510: {
        "name": "Artanis",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 119196,
            "name": "Warp Gate",
            "cost": 0,
            "text": "At the start of the game, choose from 2 Protoss minions to get after you buy 14 cards. <i>(14 left!)</i>",
        },
        "buddy": {
            "id": 122329,
            "name": "Probius",
            "attack": 8,
            "attackGold": 16,
            "health": 4,
            "healthGold": 8,
            "text": "<b>Magnetic</b> After you <b>Magnetize</b> this to a Mech, make it Golden.",
            "textGold": "<b>Magnetic</b> After you <b>Magnetize</b> this to a Mech, make it Golden.",
        },
    },
    79719: {
        "name": "Bru'kan",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 79720,
            "name": "Embrace the Elements",
            "cost": 0,
            "text": "Choose an Element. <b>Start of Combat:</b> Call upon that Element.",
        },
        "buddy": {
            "id": 77882,
            "name": "Spirit Raptor",
            "attack": 3,
            "attackGold": 6,
            "health": 2,
            "healthGold": 4,
            "text": "After you call upon a new Element, this remembers it. <b>Deathrattle:</b> Call upon those Elements.",
            "textGold": "After you call upon a new Element, this remembers it. <b>Deathrattle:</b> Call upon those Elements twice.",
        },
    },
    120649: {
        "name": "Buttons",
        "health": 30,
        "armor": 16,
        "power": {
            "id": 120650,
            "name": "Growing Collection",
            "cost": 0,
            "text": "On Turn 8, choose a Greater <b>Trinket</b> to buy. <i>(7 turns left!)</i>",
        },
        "buddy": {
            "id": 122325,
            "name": "Zippers",
            "attack": 5,
            "attackGold": 10,
            "health": 5,
            "healthGold": 10,
            "text": "<b>Deathrattle:</b> Get a helpful card.",
            "textGold": "<b>Deathrattle:</b> Get 2 helpful cards.",
        },
    },
    58535: {
        "name": "C'Thun",
        "health": 30,
        "armor": 20,
        "power": {
            "id": 66246,
            "name": "Saturday C'Thuns!",
            "cost": 1,
            "text": "At end of turn, give a friendly minion +1/+1. Repeat 0 times. <i> (Improves each turn!)</i>",
        },
        "buddy": {
            "id": 77475,
            "name": "Tentacle of C'Thun",
            "attack": 3,
            "attackGold": 6,
            "health": 3,
            "healthGold": 6,
            "text": "After a different friendly minion gains stats, gain +1/+1 until next turn.",
            "textGold": "After a different friendly minion gains stats, gain +2/+2 until next turn.",
        },
    },
    101130: {
        "name": "Cap'n Hoggarr",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 101132,
            "name": "I'm the Cap'n Now",
            "cost": 0,
            "text": "After you buy a Pirate, gain 1 Gold.",
        },
        "buddy": {
            "id": 114598,
            "name": "Shining Sailor",
            "attack": 4,
            "attackGold": 8,
            "health": 5,
            "healthGold": 10,
            "text": "<b>Divine Shield</b> The Tavern offers an extra Pirate whenever it is <b>Refreshed</b>.",
            "textGold": "<b>Divine Shield</b> The Tavern offers 2 extra Pirates whenever it is <b>Refreshed</b>.",
        },
    },
    62242: {
        "name": "Captain Eudora",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 62250,
            "name": "Buried Treasure",
            "cost": 1,
            "text": "Dig for a Golden minion! <i>(4 Digs left.)</i>",
        },
        "buddy": {
            "id": 77472,
            "name": "Dagwik Stickytoe",
            "attack": 5,
            "attackGold": 10,
            "health": 5,
            "healthGold": 10,
            "text": "At the end of your turn, give a random friendly Golden minion +5/+5.",
            "textGold": "At the end of your turn, give a random friendly Golden minion +10/+10.",
        },
    },
    62266: {
        "name": "Captain Hooktusk",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 62267,
            "name": "Trash for Treasure",
            "cost": 0,
            "text": "Remove a friendly minion. <b>Discover</b> one from a Tier lower to get.",
        },
        "buddy": {
            "id": 77776,
            "name": "Raging Contender",
            "attack": 6,
            "attackGold": 12,
            "health": 5,
            "healthGold": 10,
            "text": "After you use 'Trash for  Treasure', gain Gold equal to the removed minion's Tier.",
            "textGold": "After you use 'Trash for  Treasure', gain Gold equal to the removed minion's Tier twice.",
        },
    },
    73940: {
        "name": "Cariel Roame",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 73941,
            "name": "Conviction",
            "cost": 0,
            "text": "Give 1 random friendly minion +1/+1. <b><b>Passive</b>:</b> After each combat, choose an improvement.",
        },
        "buddy": {
            "id": 77778,
            "name": "Captain Fairmount",
            "attack": 7,
            "attackGold": 14,
            "health": 5,
            "healthGold": 10,
            "text": "At the end of your turn, randomly improve 'Conviction'.",
            "textGold": "At the end of your turn, randomly improve 'Conviction' twice.",
        },
    },
    64475: {
        "name": "Chenvaala",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 64476,
            "name": "Avalanche",
            "cost": 0,
            "text": "After you play 3 Elementals, reduce the Cost of upgrading the Tavern by (3).",
        },
        "buddy": {
            "id": 77780,
            "name": "Snow Elemental",
            "attack": 5,
            "attackGold": 10,
            "health": 4,
            "healthGold": 8,
            "text": "The Tavern offers an extra <b>Frozen</b> Elemental whenever it is <b>Refreshed</b>.",
            "textGold": "The Tavern offers 2 extra <b>Frozen</b> Elementals whenever it is <b>Refreshed</b>.",
        },
    },
    104981: {
        "name": "Cho",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 104985,
            "name": "Double Trouble",
            "cost": 0,
            "text": "Whenever you play a Golden minion, both you and Cho get a Triple Reward. <i>(3 left!)</i>",
        },
        "buddy": {
            "id": 113690,
            "name": "Halfus the Mighty",
            "attack": 5,
            "attackGold": 10,
            "health": 5,
            "healthGold": 10,
            "text": "At the start of your turn, <b>Discover</b> a minion of your Tier. <i>(50% chance to <b>Pass</b> it!)</i>",
            "textGold": "At the start of your turn, <b>Discover</b> 2 minions of your Tier. <i>(50% chance to <b>Pass</b> them!)</i>",
        },
    },
    77516: {
        "name": "Cookie the Cook",
        "health": 30,
        "armor": 8,
        "power": {
            "id": 77434,
            "name": "Stir the Pot",
            "cost": 0,
            "text": "Throw a minion in your pot. When you've gathered 3, <b>Discover</b> from their types. <i>(3 left!)</i>",
        },
        "buddy": {
            "id": 77872,
            "name": "Sous Chef",
            "attack": 2,
            "attackGold": 4,
            "health": 5,
            "healthGold": 10,
            "text": "You can use your Hero Power an extra time each turn.",
            "textGold": "You can use your Hero Power 2 extra times each turn.",
        },
    },
    59806: {
        "name": "Dancin' Deryl",
        "health": 30,
        "armor": 16,
        "power": {
            "id": 59860,
            "name": "Hat Trick",
            "cost": 0,
            "text": "When you play a minion, give it a +1/+1 hat  that passes to a friendly minion when sold.",
        },
        "buddy": {
            "id": 77477,
            "name": "Asher the Haberdasher",
            "attack": 2,
            "attackGold": 4,
            "health": 2,
            "healthGold": 4,
            "text": "After you sell a minion, gain two +1/+1 hats that pass to a friendly minion when sold.",
            "textGold": "After you sell a minion, gain four +1/+1 hats that pass to a friendly minion when sold.",
        },
    },
    71458: {
        "name": "Death Speaker Blackthorn",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 71459,
            "name": "Bloodbound",
            "cost": 1,
            "text": "Get 2 <b>Blood Gems</b>. <i>(Twice per turn.)</i>",
        },
        "buddy": {
            "id": 77478,
            "name": "Death's Head Sage",
            "attack": 3,
            "attackGold": 6,
            "health": 7,
            "healthGold": 14,
            "text": "After you get a <b>Blood Gem</b>, get an extra copy of it.",
            "textGold": "After you get a <b>Blood Gem</b>, get 2 extra copies of it.",
        },
    },
    60369: {
        "name": "Deathwing",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 61406,
            "name": "ALL Will Burn!",
            "cost": 0,
            "text": "<b>Start of Combat:</b> Give ALL minions +2 Attack permanently.",
        },
        "buddy": {
            "id": 77782,
            "name": "Sinestra",
            "attack": 2,
            "attackGold": 4,
            "health": 6,
            "healthGold": 12,
            "text": "Whenever a friendly minion gains Attack during combat, give it +1 Health permanently.",
            "textGold": "Whenever a friendly minion gains Attack during combat, give it +2 Health permanently.",
        },
    },
    60214: {
        "name": "Dinotamer Brann",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 60218,
            "name": "Battle Brand",
            "cost": 0,
            "text": "After you buy 4 <b>Battlecry</b> minions, get a Brann Bronzebeard. <i>(Once per game.)</i>",
        },
        "buddy": {
            "id": 77784,
            "name": "Brann's Epic Egg",
            "attack": 0,
            "health": 3,
            "healthGold": 6,
            "text": "<b>Taunt</b>  <b>Deathrattle:</b> Summon and get a random <b>Battlecry</b> minion.",
            "textGold": "<b>Taunt</b>  <b>Deathrattle:</b> Summon and get 2 random <b>Battlecry</b> minions.",
        },
    },
    105434: {
        "name": "Doctor Holli'dae",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 110472,
            "name": "Blessing of the Nine Frogs",
            "cost": 1,
            "text": "Get a random Tavern spell.",
        },
        "buddy": {
            "id": 113631,
            "name": "The Nine Frogs",
            "attack": 9,
            "attackGold": 18,
            "health": 9,
            "healthGold": 18,
            "text": "After you buy a minion, get a random Tavern spell from the same Tier. <i>(9 left!)</i>",
            "textGold": "After you buy a minion, get 2 random Tavern spells from the same Tier. <i>(9 left!)</i>",
        },
    },
    80239: {
        "name": "Drek'Thar",
        "health": 30,
        "armor": 10,
        "power": {
            "id": 80244,
            "name": "Frostwolf Fervor",
            "cost": 0,
            "text": "When you have space in combat, summon a copy of your highest-Attack minion. <i>(Unlocks on Turn 7.)</i>",
        },
        "buddy": {
            "id": 77884,
            "name": "Frostwolf Lieutenant",
            "attack": 7,
            "attackGold": 14,
            "health": 4,
            "healthGold": 8,
            "text": "At the end of your turn, give your left-most minion +10 Attack.",
            "textGold": "At the end of your turn, give your left-most minion +20 Attack.",
        },
    },
    101345: {
        "name": "E.T.C., Band Manager",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 101346,
            "name": "Sign a New Artist",
            "cost": 3,
            "text": "<b>Discover</b> a <b>Buddy</b>. <i>(Unlocks at Tier 2.)</i>",
        },
        "buddy": {
            "id": 101349,
            "name": "Talent Scout",
            "attack": 4,
            "attackGold": 8,
            "health": 4,
            "healthGold": 8,
            "text": "<b>Battlecry:</b> Make a <b>Buddy</b> Golden.",
            "textGold": "<b>Battlecry:</b> Make 2 <b>Buddies</b> Golden.",
        },
    },
    57633: {
        "name": "Edwin VanCleef",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 57567,
            "name": "Sharpen Blades",
            "cost": 1,
            "text": "Give a minion +2/+2. Improves after you buy 4 cards. <i>(4 left!)</i>",
        },
        "buddy": {
            "id": 77479,
            "name": "SI:7 Scout",
            "attack": 2,
            "attackGold": 4,
            "health": 2,
            "healthGold": 4,
            "text": "After you buy a card, gain +2/+2.",
            "textGold": "After you buy a card, gain +4/+4.",
        },
    },
    60213: {
        "name": "Elise Starseeker",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 60217,
            "name": "Lead Explorer",
            "cost": 1,
            "text": "<b>Discover</b> a minion from your Tier. Costs (1) more after each use.",
        },
        "buddy": {
            "id": 77484,
            "name": "Jr. Navigator",
            "attack": 4,
            "attackGold": 8,
            "health": 4,
            "healthGold": 8,
            "text": "<b>Battlecry:</b> Reduce the Cost of 'Lead Explorer' by (2).",
            "textGold": "<b>Battlecry:</b> Reduce the Cost of 'Lead Explorer' by (4).",
        },
    },
    96870: {
        "name": "Enhance-o Mechano",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 96872,
            "name": "Enhancification",
            "cost": 0,
            "text": "After the Tavern is <b>Refreshed</b>, give a random minion in it a random <b>Bonus Keyword</b>, twice.",
        },
        "buddy": {
            "id": 101973,
            "name": "Enhance-o Medico",
            "attack": 3,
            "attackGold": 6,
            "health": 3,
            "healthGold": 6,
            "text": "After you buy a minion, gain +3/+3 for each <b>Bonus Keyword</b> it has.",
            "textGold": "After you buy a minion, gain +6/+6 for each <b>Bonus Keyword</b> it has.",
        },
    },
    117425: {
        "name": "Exarch Othaar",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 117426,
            "name": "Arcane Knowledge",
            "cost": 0,
            "text": "The next Tavern spell you buy costs (1) less. <i>(Unlocks on Turn 3.)</i>",
        },
        "buddy": {
            "id": 122342,
            "name": "The Celestial Archive",
            "attack": 4,
            "attackGold": 8,
            "health": 4,
            "healthGold": 8,
            "text": "Whenever you buy a Tavern spell that costs (0), get a copy of it.",
            "textGold": "Whenever you buy a Tavern spell that costs (0), get two copies of it.",
        },
    },
    116926: {
        "name": "Farseer Nobundo",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 116924,
            "name": "The Galaxy's Lens",
            "cost": 3,
            "text": "Get a copy of the last Tavern spell you cast. Each turn, your next Hero Power costs (1) less.",
        },
        "buddy": {
            "id": 122331,
            "name": "Outland Sunbeam",
            "attack": 5,
            "attackGold": 10,
            "health": 5,
            "healthGold": 10,
            "text": "<b>Battlecry:</b> <b>Discover</b> a Tavern spell that costs (3) or more from any Tier.",
            "textGold": "<b>Battlecry:</b> <b>Discover</b> two Tavern spells that cost (3) or more from any Tier.",
        },
    },
    104671: {
        "name": "Flobbidinous Floop",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 104672,
            "name": "Glorious Gloop",
            "cost": 0,
            "text": "Choose a friendly minion. <b>Start of Combat:</b> Transform it into your teammate's highest-Tier minion.",
        },
        "buddy": {
            "id": 113637,
            "name": "Glorious Gloopling",
            "attack": 7,
            "attackGold": 14,
            "health": 7,
            "healthGold": 14,
            "text": "At the start of every 2 turns, get a plain copy of your teammate's highest-Tier minion <i>(2 turns left!)</i>",
            "textGold": "At the start of every 2 turns, get two plain copies of your teammate's highest-Tier minion <i>(2 turns left!)</i>",
        },
    },
    116920: {
        "name": "Forest Lord Cenarius",
        "health": 30,
        "armor": 16,
        "power": {
            "id": 116921,
            "name": "Wisdom of Ancients",
            "cost": 3,
            "text": "Increase your maximum Gold by 1.",
        },
        "buddy": {
            "id": 122335,
            "name": "Malorne",
            "attack": 1,
            "attackGold": 2,
            "health": 1,
            "healthGold": 2,
            "text": "Has +1/+1 for every 3 Gold you've spent this game.",
            "textGold": "Has +2/+2 for every 3 Gold you've spent this game.",
        },
    },
    63604: {
        "name": "Forest Warden Omu",
        "health": 30,
        "armor": 6,
        "power": {
            "id": 63605,
            "name": "Everbloom",
            "cost": 0,
            "text": "After you upgrade the Tavern, gain 2 Gold.",
        },
        "buddy": {
            "id": 77493,
            "name": "Evergreen Botani",
            "attack": 8,
            "attackGold": 16,
            "health": 5,
            "healthGold": 10,
            "text": "At the end of your turn, get a random minion of your Tier.",
            "textGold": "At the end of your turn, get two random minions of your Tier.",
        },
    },
    60372: {
        "name": "Fungalmancer Flurgl",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 60448,
            "name": "Gone Fishing",
            "cost": 0,
            "text": "After you sell 5 minions, get a random Murloc. <i>(5 left!)</i>",
        },
        "buddy": {
            "id": 77786,
            "name": "Sparkfin Soothsayer",
            "attack": 4,
            "attackGold": 8,
            "health": 3,
            "healthGold": 6,
            "text": "<b>Battlecry:</b> Transform minions in the Tavern into Murlocs of the same Tier.",
            "textGold": "<b>Battlecry:</b> Transform minions in the Tavern into Murlocs of a Tier higher.",
        },
    },
    57635: {
        "name": "Galakrond",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 57555,
            "name": "Galakrond's Greed",
            "cost": 1,
            "text": "Choose a minion in the Tavern. Then choose a higher Tier minion to replace it.",
        },
        "buddy": {
            "id": 77494,
            "name": "Apostle of Galakrond",
            "attack": 2,
            "attackGold": 4,
            "health": 4,
            "healthGold": 8,
            "text": "<b>Battlecry:</b> Replace cards in the Tavern with ones from a Tier higher.",
            "textGold": "<b>Battlecry:</b> Replace cards in the Tavern with ones from 2 Tiers higher.",
        },
    },
    75702: {
        "name": "Galewing",
        "health": 30,
        "armor": 10,
        "power": {
            "id": 75703,
            "name": "Dungar's Gryphon",
            "cost": 0,
            "text": "Choose a new flightpath. Complete it to get a bonus!",
        },
        "buddy": {
            "id": 77788,
            "name": "Flight Trainer",
            "attack": 2,
            "attackGold": 4,
            "health": 2,
            "healthGold": 4,
            "text": "Your flightpaths trigger twice.",
            "textGold": "Your flightpaths trigger three times.",
        },
    },
    104982: {
        "name": "Gall",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 104983,
            "name": "Double Trouble",
            "cost": 0,
            "text": "Whenever you play a Golden minion, both you and Gall get a Triple Reward. <i>(3 left!)</i>",
        },
        "buddy": {
            "id": 113692,
            "name": "Halfus the Wise",
            "attack": 5,
            "attackGold": 10,
            "health": 5,
            "healthGold": 10,
            "text": "At the start of your turn, <b>Discover</b> a Tavern spell of your Tier. <i>(50% chance to <b>Pass</b> it!)</i>",
            "textGold": "At the start of your turn, <b>Discover</b> 2 Tavern spells of your Tier. <i>(50% chance to <b>Pass</b> them!)</i>",
        },
    },
    129684: {
        "name": "Genn, Worgen King",
        "health": 30,
        "armor": 7,
        "power": {
            "id": 129685,
            "name": "King of Duality",
            "cost": 0,
            "text": "On Turn 4, <b>Discover</b> two Hero Powers to replace this. <i>(3 turns left!)</i>",
        },
    },
    57929: {
        "name": "George the Fallen",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 57562,
            "name": "Boon of Light",
            "cost": 1,
            "text": "Give a minion <b>Divine Shield</b>.",
        },
        "buddy": {
            "id": 77495,
            "name": "Karl the Lost",
            "attack": 3,
            "attackGold": 6,
            "health": 4,
            "healthGold": 8,
            "text": "After you use your Hero Power, give your <b>Divine Shield</b> minions +2 Attack.",
            "textGold": "After you use your Hero Power, give your <b>Divine Shield</b> minions +4 Attack.",
        },
    },
    67553: {
        "name": "Greybough",
        "health": 30,
        "armor": 16,
        "power": {
            "id": 67554,
            "name": "Sprout It Out!",
            "cost": 0,
            "text": "Give +1/+2 and <b>Taunt</b> to minions you summon during combat.",
        },
        "buddy": {
            "id": 77502,
            "name": "Wandering Treant",
            "attack": 3,
            "attackGold": 6,
            "health": 9,
            "healthGold": 18,
            "text": "Whenever a friendly <b>Taunt</b> minion is attacked, give your minions +1/+1 permanently.",
            "textGold": "Whenever a friendly <b>Taunt</b> minion is attacked, give your minions +2/+2 permanently.",
        },
    },
    68129: {
        "name": "Guff Runetotem",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 68130,
            "name": "Natural Balance",
            "cost": 0,
            "text": "After you buy 20 Tiers' worth of cards, get a Triple Reward. <i>(20 left!)</i>",
        },
        "buddy": {
            "id": 77790,
            "name": "Baby Kodo",
            "attack": 3,
            "attackGold": 6,
            "health": 6,
            "healthGold": 12,
            "text": "<b>Battlecry: Refresh</b> the Tavern with a minion of each Tier.",
            "textGold": "<b>Battlecry: Refresh</b> the Tavern with a minion of each Tier.",
        },
    },
    86291: {
        "name": "Heistbaron Togwaggle",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 86292,
            "name": "The Perfect Crime",
            "cost": 11,
            "text": "Steal all cards from the Tavern. Each turn, your next Hero Power costs (1) less.",
        },
        "buddy": {
            "id": 98650,
            "name": "Waxadred, the Drippy",
            "attack": 7,
            "attackGold": 14,
            "health": 5,
            "healthGold": 10,
            "text": "<b><b>Battlecry:</b> Refresh</b> the Tavern with the highest- Tier minion from each opponent's warband.",
            "textGold": "<b><b>Battlecry:</b> Refresh</b> the Tavern with the highest- Tier minion from each opponent's warband.",
        },
    },
    57634: {
        "name": "Illidan Stormrage",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 61851,
            "name": "Wingmen",
            "cost": 0,
            "text": "<b>Start of Combat:</b> Your left- and right-most minions gain +2/+1 and attack immediately.",
        },
        "buddy": {
            "id": 77626,
            "name": "Eclipsion Illidari",
            "attack": 6,
            "attackGold": 12,
            "health": 3,
            "healthGold": 6,
            "text": "Your first minion that attacks has \"<b>Immune</b> while Attacking\" for one attack only.",
            "textGold": "Your first two minions that attack have \"<b>Immune</b> while Attacking\" for one attack only.",
        },
    },
    58534: {
        "name": "Infinite Toki",
        "health": 30,
        "armor": 10,
        "power": {
            "id": 58537,
            "name": "Temporal Tavern",
            "cost": 1,
            "text": "<b>Refresh</b> the Tavern. Include two minions from a Tier higher than yours.",
        },
        "buddy": {
            "id": 77507,
            "name": "Clockwork Assistant",
            "attack": 3,
            "attackGold": 6,
            "health": 3,
            "healthGold": 6,
            "text": "<b>Battlecry:</b> <b>Discover</b> a minion from a Tier higher than yours.",
            "textGold": "<b>Battlecry:</b> <b>Discover</b> two minions from a Tier higher than yours.",
        },
    },
    103500: {
        "name": "Inge, the Iron Hymn",
        "health": 30,
        "armor": 17,
        "power": {
            "id": 103501,
            "name": "Major Hymn",
            "cost": 0,
            "text": "Twice per turn, give a minion Attack equal to your Tier. <i>(Swaps to Health next turn!)</i>",
        },
        "buddy": {
            "id": 113627,
            "name": "Solemn Serenader",
            "attack": 6,
            "attackGold": 12,
            "health": 5,
            "healthGold": 10,
            "text": "After you use your Hero Power on a minion, it gains half this minion's Attack. <i>(Swaps to Health next turn!)</i>",
            "textGold": "After you use your Hero Power on a minion, it gains this minion's Attack. <i>(Swaps to Health next turn!)</i>",
        },
    },
    80832: {
        "name": "Ini Stormcoil",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 81572,
            "name": "MechGyver",
            "cost": 0,
            "text": "After 9 friendly minions die, get a random Mech.",
        },
        "buddy": {
            "id": 82600,
            "name": "Sub Scrubber",
            "attack": 6,
            "attackGold": 12,
            "health": 6,
            "healthGold": 12,
            "text": "After you play a Mech, gain +3/+3.",
            "textGold": "After you play a Mech, gain +6/+6.",
        },
    },
    63601: {
        "name": "Jandice Barov",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 63607,
            "name": "Swap, Lock, & Shop It",
            "cost": 0,
            "text": "Swap a friendly non-Golden minion with a random one in the Tavern.",
        },
        "buddy": {
            "id": 77792,
            "name": "Jandice's Apprentice",
            "attack": 5,
            "attackGold": 10,
            "health": 6,
            "healthGold": 12,
            "text": "After you play a minion you've already played this turn, give your minions stats equal to your Tier.",
            "textGold": "After you play a minion you've already played this turn, give your minions stats equal to twice your Tier.",
        },
    },
    118509: {
        "name": "Jim Raynor",
        "health": 30,
        "armor": 16,
        "power": {
            "id": 118681,
            "name": "Lift Off",
            "cost": 0,
            "text": "Start the game with a 2/2 Battlecruiser. Whenever the Tavern is <b>Refreshed</b>, add a Battlecruiser Upgrade to it.",
        },
        "buddy": {
            "id": 122369,
            "name": "Tychus Findlay",
            "attack": 4,
            "attackGold": 8,
            "health": 6,
            "healthGold": 12,
            "text": "After you cast two Tavern spells, get a random Battlecruiser Upgrade. <i>(2 left!)</i>",
            "textGold": "After you cast two Tavern spells, get 2 random Battlecruiser Upgrades. <i>(2 left!)</i>",
        },
    },
    61912: {
        "name": "Kael'thas Sunstrider",
        "health": 30,
        "armor": 16,
        "power": {
            "id": 61917,
            "name": "Verdant Spheres",
            "cost": 0,
            "text": "After you buy 3 minions, get a Tavern Coin.",
        },
        "buddy": {
            "id": 77794,
            "name": "Crimson Hand Centurion",
            "attack": 3,
            "attackGold": 6,
            "health": 3,
            "healthGold": 6,
            "text": "<b>Divine Shield</b>. After 'Verdant Spheres' triggers, gain the stats of the last minion you bought.",
            "textGold": "<b><b>Divine Shield</b>.</b> After 'Verdant Spheres' triggers, gain double the stats of the last minion you bought.",
        },
    },
    120358: {
        "name": "Kerrigan, Queen of Blades",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 120362,
            "name": "Spawning Pool",
            "cost": 6,
            "text": "Unlock Tier 2 Zerg. Costs (1) less each turn. <b><b>Passive</b>:</b> Start the game with a 2/2 Larva.",
        },
        "buddy": {
            "id": 122333,
            "name": "Broken Horn",
            "attack": 4,
            "attackGold": 8,
            "health": 4,
            "healthGold": 8,
            "text": "When you sell this, <b>Discover</b> a Zerg minion and set its stats to 6/6.  It doesn't morph.",
            "textGold": "When you sell this, <b>Discover</b> two Zerg minions and set their stats to 6/6. They don't morph.",
        },
    },
    59814: {
        "name": "King Mukla",
        "health": 30,
        "armor": 16,
        "power": {
            "id": 59815,
            "name": "Bananarama",
            "cost": 0,
            "text": "At the start of your turn, get 2 Bananas and give everyone else one.",
        },
        "buddy": {
            "id": 77508,
            "name": "Crazy Monkey",
            "attack": 1,
            "attackGold": 2,
            "health": 4,
            "healthGold": 8,
            "text": "When you sell this, feed 1 Banana to your minions. After you cast 2 spells, improve this. <i>(2 left!)</i>",
            "textGold": "When you sell this, feed 2 Banana to your minions. After you cast 2 spells, improve this. <i>(2 left!)</i>",
        },
    },
    74631: {
        "name": "Kurtrus Ashfallen",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 104875,
            "name": "Glaive Ricochet",
            "cost": 0,
            "text": "Once per turn, after you buy 3 minions, get a plain copy of one of them. <i>(3 left!)</i>",
        },
        "buddy": {
            "id": 77796,
            "name": "Living Nightmare",
            "attack": 4,
            "attackGold": 8,
            "health": 4,
            "healthGold": 8,
            "text": "After you buy a card, minions in the Tavern have +2/+2 this turn.",
            "textGold": "After you buy a card, minions in the Tavern have +4/+4 this turn.",
        },
    },
    85125: {
        "name": "Lady Vashj",
        "health": 30,
        "armor": 16,
        "power": {
            "id": 85126,
            "name": "Relics of the Deep",
            "cost": 0,
            "text": "At the start of each turn, get a random <b>Spellcraft</b> spell.",
        },
        "buddy": {
            "id": 101458,
            "name": "Coilfang Elite",
            "attack": 3,
            "attackGold": 6,
            "health": 2,
            "healthGold": 4,
            "text": "After a <b>Spellcraft</b> minion appears in the Tavern, get a copy of its spell.",
            "textGold": "After a <b>Spellcraft</b> minion appears in the Tavern, get 2 copies of its spell.",
        },
    },
    58044: {
        "name": "Lich Baz'hial",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 60285,
            "name": "Graveyard Shift",
            "cost": 2,
            "text": "Steal a card from the Tavern. Take 2 damage.",
        },
        "buddy": {
            "id": 77510,
            "name": "Unearthed Underling",
            "attack": 5,
            "attackGold": 10,
            "health": 5,
            "healthGold": 10,
            "text": "Whenever your hero takes damage, rewind it and gain stats equal to that amount.",
            "textGold": "Whenever your hero takes damage, rewind it and gain stats equal to double that amount.",
        },
    },
    122925: {
        "name": "Loh, the Living Legend",
        "health": 30,
        "armor": 17,
        "power": {
            "id": 129164,
            "name": "Heroic Inspiration",
            "cost": 0,
            "text": "After 15 friendly minions attack, get a Triple Reward. <i>(15 left!)</i>",
        },
        "buddy": {
            "id": 123075,
            "name": "Stoneshell Guardian",
            "attack": 5,
            "attackGold": 10,
            "health": 5,
            "healthGold": 10,
            "text": "The first Triple Reward you play each turn <b><b>Discover</b>s</b> from Golden minions. <i>(1 left!)</i>",
            "textGold": "The first two Triple Rewards you play each turn <b>Discover</b> from Golden minions. <i>(2 left!)</i>",
        },
    },
    63602: {
        "name": "Lord Barov",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 63600,
            "name": "Friendly Wager",
            "cost": 1,
            "text": "Guess which player will win their next combat. If you're correct, get 3 Tavern Coins.",
        },
        "buddy": {
            "id": 77511,
            "name": "Barov's Apprentice",
            "attack": 5,
            "attackGold": 10,
            "health": 4,
            "healthGold": 8,
            "text": "After you play a Coin, gain 1 Gold.",
            "textGold": "After you play a Coin, gain 2 Gold.",
        },
    },
    59807: {
        "name": "Lord Jaraxxus",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 59808,
            "name": "Bloodfury",
            "cost": 0,
            "text": "After friendly minions deal 150 damage, open a portal to the Twisting Nether! <i>(150 left!)</i>",
        },
    },
    107183: {
        "name": "Madam Goya",
        "health": 30,
        "armor": 8,
        "power": {
            "id": 107184,
            "name": "Efficient Exchange",
            "cost": 2,
            "text": "<b>Pass</b> a non-Golden minion.",
        },
        "buddy": {
            "id": 113635,
            "name": "Mister Chu",
            "attack": 5,
            "attackGold": 10,
            "health": 5,
            "healthGold": 10,
            "text": "At the end of your turn, <b>Pass</b> the highest-Tier minion in the Tavern.",
            "textGold": "At the end of your turn, <b>Pass</b> the 2 highest-Tier minions in the Tavern.",
        },
    },
    61914: {
        "name": "Maiev Shadowsong",
        "health": 30,
        "armor": 17,
        "power": {
            "id": 61919,
            "name": "Imprison",
            "cost": 1,
            "text": "Choose a card in the Tavern to lock in your hand. After 2 turns, unlock it.",
        },
        "buddy": {
            "id": 77800,
            "name": "Shadow Warden",
            "attack": 5,
            "attackGold": 10,
            "health": 5,
            "healthGold": 10,
            "text": "<b>Battlecry:</b> Your next Hero Power makes the target Golden.",
            "textGold": "<b>Battlecry:</b> Your next 2 Hero Powers make the target Golden.",
        },
    },
    61490: {
        "name": "Malygos",
        "health": 30,
        "armor": 17,
        "power": {
            "id": 60378,
            "name": "Arcane Alteration",
            "cost": 0,
            "text": "Replace a card with a  random one of the same Tier. <i>(Twice per turn.)</i>",
        },
        "buddy": {
            "id": 77723,
            "name": "Nexus Lord",
            "attack": 6,
            "attackGold": 12,
            "health": 6,
            "healthGold": 12,
            "text": "'Arcane Alteration' replaces with a card from one Tier higher.",
            "textGold": "'Arcane Alteration' replaces with a card from two Tiers higher.",
        },
    },
    113310: {
        "name": "Marin the Manager",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 113311,
            "name": "Fantastic Treasure",
            "cost": 0,
            "text": "On Turn 5, choose a Lesser <b>Trinket</b> to buy. <i>(4 turns left!)</i>",
        },
        "buddy": {
            "id": 122323,
            "name": "Fantastic Bellhop",
            "attack": 6,
            "attackGold": 12,
            "health": 6,
            "healthGold": 12,
            "text": "At the end of your turn, get a helpful card.",
            "textGold": "At the end of your turn, get 2 helpful cards.",
        },
    },
    71908: {
        "name": "Master Nguyen",
        "health": 30,
        "armor": 10,
        "power": {
            "id": 71909,
            "name": "Power of the Storm",
            "cost": 0,
            "text": "At the start of every turn, choose from 2 new Hero Powers.",
        },
        "buddy": {
            "id": 77514,
            "name": "Lei Flamepaw",
            "attack": 4,
            "attackGold": 8,
            "health": 6,
            "healthGold": 12,
            "text": "At the start of your turn, get the <b>Buddy</b> of your Hero Power.",
            "textGold": "At the start of your turn, get 2 copies of the <b>Buddy</b> of your Hero Power.",
        },
    },
    60366: {
        "name": "Millhouse Manastorm",
        "health": 30,
        "armor": 16,
        "power": {
            "id": 60405,
            "name": "Manastorm",
            "cost": 0,
            "text": "Minions and <b>Refreshes</b> cost 2 Gold. Upgrading the Tavern costs (1) more.",
        },
        "buddy": {
            "id": 77803,
            "name": "Magnus Manastorm",
            "attack": 4,
            "attackGold": 8,
            "health": 4,
            "healthGold": 8,
            "text": "Two <b>Refreshes</b> each turn are free. <i>(0 left!)</i>",
            "textGold": "Four <b>Refreshes</b> each turn are free. <i>(0 left!)</i>",
        },
    },
    57946: {
        "name": "Millificent Manastorm",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 57949,
            "name": "Tinker",
            "cost": 1,
            "text": "<b>Discover</b> a <b>Magnetic</b> Mech. <i>(Unlocks at Tier 4.)</i>",
        },
        "buddy": {
            "id": 77805,
            "name": "Elementium Squirrel Bomb",
            "attack": 4,
            "attackGold": 8,
            "health": 4,
            "healthGold": 8,
            "text": "<b>Deathrattle:</b> Deal 4 damage to a random enemy minion for each of your Mechs that died this combat.",
            "textGold": "<b>Deathrattle:</b> Deal 8 damage to a random enemy minion for each of your Mechs that died this combat.",
        },
    },
    126532: {
        "name": "Mister Clocksworth",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 126533,
            "name": "Double Time",
            "cost": 0,
            "text": "You only need 2 copies to make minions Golden.  They give Tavern Coins instead of Triple Rewards.",
        },
    },
    129173: {
        "name": "Morchie",
        "health": 30,
        "armor": 8,
        "power": {
            "id": 129174,
            "name": "Warped Conflux",
            "cost": 0,
            "text": "On Turn 5, visit the Minor <b>Timewarp</b>. <i>(4 turns left!)</i>",
        },
    },
    63319: {
        "name": "Mr. Bigglesworth",
        "health": 30,
        "armor": 19,
        "power": {
            "id": 63320,
            "name": "Kel'Thuzad's Kitty",
            "cost": 0,
            "text": "After another hero dies, <b>Discover</b> a minion from their warband. It keeps enchantments.",
        },
        "buddy": {
            "id": 77807,
            "name": "Lil' K.T.",
            "attack": 5,
            "attackGold": 10,
            "health": 4,
            "healthGold": 8,
            "text": "At the start of your turn, get a plain minion from your lowest-Health opponent's warband.",
            "textGold": "At the start of your turn, get 2 plain minions from your lowest-Health opponent's warband.",
        },
    },
    84867: {
        "name": "Murloc Holmes",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 90403,
            "name": "Detective for Hire",
            "cost": 0,
            "text": "Look at 2 minions. Guess which one your next opponent had last combat for a Tavern Coin.",
        },
        "buddy": {
            "id": 98656,
            "name": "Watfin",
            "attack": 2,
            "attackGold": 4,
            "health": 5,
            "healthGold": 10,
            "text": "After you guess correctly with 'Detective for Hire', get a plain copy of the minion.",
            "textGold": "After you guess correctly with 'Detective for Hire', get 2 plain copies of the minion.",
        },
    },
    127696: {
        "name": "Murozond, Unbounded",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 127697,
            "name": "Alternate Timeline",
            "cost": 0,
            "text": "On Turn 8, visit the Major <b>Timewarp</b>. <i>(7 turns left!)</i>",
        },
    },
    71916: {
        "name": "Mutanus the Devourer",
        "health": 30,
        "armor": 20,
        "power": {
            "id": 71914,
            "name": "Devour",
            "cost": 0,
            "text": "Sell a friendly minion. Spit its stats onto another.",
        },
        "buddy": {
            "id": 77809,
            "name": "Nightmare Ectoplasm",
            "attack": 6,
            "attackGold": 12,
            "health": 6,
            "healthGold": 12,
            "text": "When you 'Devour' this, spit its stats onto 1 extra minion.",
            "textGold": "When you 'Devour' this, spit its stats onto 2 extra minions.",
        },
    },
    66483: {
        "name": "N'Zoth",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 66484,
            "name": "Avatar of N'Zoth",
            "cost": 0,
            "text": "Start the game with a 2/2 Fish that gains all your <b>Deathrattles</b> in combat.",
        },
        "buddy": {
            "id": 77811,
            "name": "Baby N'Zoth",
            "attack": 8,
            "attackGold": 16,
            "health": 4,
            "healthGold": 8,
            "text": "<b>Battlecry:</b> Make a friendly <b>Deathrattle</b> minion Golden.",
            "textGold": "<b>Battlecry:</b> Make all friendly <b>Deathrattle</b> minions Golden.",
        },
    },
    132608: {
        "name": "Nightmare Lord Xavius",
        "health": 30,
        "armor": 6,
        "power": {
            "id": 134010,
            "name": "Feel Devastation",
            "cost": 0,
            "text": "Every 4 turns, <b>Discover</b> a minion with a <b>Dark Gift</b>. <i>(3 turns left!)</i>",
        },
    },
    61489: {
        "name": "Nozdormu",
        "health": 30,
        "armor": 13,
        "power": {
            "id": 61491,
            "name": "Clairvoyance",
            "cost": 0,
            "text": "At the start of your turn, gain a free <b>Refresh</b>.",
        },
        "buddy": {
            "id": 77512,
            "name": "Chromie",
            "attack": 6,
            "attackGold": 12,
            "health": 6,
            "healthGold": 12,
            "text": "One <b>Refresh</b> each turn is helpful! <i>(1 left!)</i>",
            "textGold": "Two <b>Refreshes</b> each turn are helpful! <i>(2 left!)</i>",
        },
    },
    82110: {
        "name": "Onyxia",
        "health": 30,
        "armor": 10,
        "power": {
            "id": 82114,
            "name": "Broodmother",
            "cost": 0,
            "text": "<b>Avenge (4):</b> Summon a 1/1 Whelp that attacks immediately. Improve this by +1/+1.",
        },
        "buddy": {
            "id": 77890,
            "name": "Many Whelps",
            "attack": 4,
            "attackGold": 8,
            "health": 2,
            "healthGold": 4,
            "text": "Whenever you summon a Whelp, gain +2/+2 permanently.",
            "textGold": "Whenever you summon a Whelp, gain +4/+4 permanently.",
        },
    },
    71454: {
        "name": "Overlord Saurfang",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 71455,
            "name": "For the Horde!",
            "cost": 0,
            "text": "Minions in the Tavern have +1/+1. Improves after you buy 3 minions. <i>(3 left!)</i>",
        },
        "buddy": {
            "id": 77813,
            "name": "Dranosh Saurfang",
            "attack": 6,
            "attackGold": 12,
            "health": 6,
            "healthGold": 12,
            "text": "After you buy a minion, gain half its stats.",
            "textGold": "After you buy a minion, gain its stats.",
        },
    },
    86013: {
        "name": "Ozumat",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 86014,
            "name": "Tentacular",
            "cost": 0,
            "text": "When you have space in combat, summon a 2/2 Tentacle with <b>Taunt</b>. <i>(Gains +1/+1 after you sell a minion!)</i>",
        },
        "buddy": {
            "id": 98635,
            "name": "Tamuzo",
            "attack": 4,
            "attackGold": 8,
            "health": 4,
            "healthGold": 8,
            "text": "After you summon a minion in combat, double its stats.",
            "textGold": "After you summon a minion in combat, triple its stats.",
        },
    },
    57947: {
        "name": "Patches the Pirate",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 62243,
            "name": "Pirate Parrrrty!",
            "cost": 3,
            "text": "Get a Pirate. After you buy a Pirate, your next Hero Power costs (1) less.",
        },
        "buddy": {
            "id": 77815,
            "name": "Tuskarr Raider",
            "attack": 6,
            "attackGold": 12,
            "health": 6,
            "healthGold": 12,
            "text": "<b>Battlecry, Deathrattle, and Rally:</b> Get a random <b>Bounty</b>.",
            "textGold": "<b>Battlecry, Deathrattle, and Rally:</b> Get 2 random <b>Bounties</b>.",
        },
    },
    59397: {
        "name": "Patchwerk",
        "health": 60,
        "armor": None,
        "power": {
            "id": 59399,
            "name": "All Patched Up",
            "cost": 0,
            "text": "Start the game with 30 extra Health.",
        },
        "buddy": {
            "id": 77817,
            "name": "Weebomination",
            "attack": 6,
            "attackGold": 12,
            "health": 6,
            "healthGold": 12,
            "text": "At the end of your turn, give the minion to the left +1 Health. <i>(Improved by each Health your hero is missing!)</i>",
            "textGold": "At the end of your turn, give adjacent minions +1 Health. <i>(Improved by each Health your hero is missing!)</i>",
        },
    },
    97813: {
        "name": "Professor Putricide",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 97814,
            "name": "Build-An-Undead",
            "cost": 3,
            "text": "Craft a custom Undead. <i>(3 Creations left!)</i>",
        },
        "buddy": {
            "id": 101442,
            "name": "Festergut",
            "attack": 6,
            "attackGold": 12,
            "health": 2,
            "healthGold": 4,
            "text": "<b>Deathrattle:</b> Summon and get a random Undead Creation.",
            "textGold": "<b>Deathrattle:</b> Summon and get 2 random Undead Creations.",
        },
    },
    59831: {
        "name": "Pyramad",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 59832,
            "name": "Brick by Brick",
            "cost": 2,
            "text": "Steal a random minion from the Tavern. Double its Health.",
        },
        "buddy": {
            "id": 77819,
            "name": "Titanic Guardian",
            "attack": 5,
            "attackGold": 10,
            "health": 2,
            "healthGold": 4,
            "text": "Whenever a different minion in your hand or board gains Health, this also gains it.",
            "textGold": "Whenever a different minion in your hand or board gains Health, this also gains twice that amount.",
        },
    },
    79618: {
        "name": "Queen Azshara",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 79619,
            "name": "Azshara's Ambition",
            "cost": 0,
            "text": "When your warband reaches 30 total Attack, begin your Naga Conquest.",
        },
    },
    57924: {
        "name": "Queen Wagtoggle",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 59863,
            "name": "Wax Warband",
            "cost": 0,
            "text": "<b>Start of Combat:</b> Give a friendly minion of each type +1/+1. <i>(Improves after you spend 10 Gold!)</i>",
        },
        "buddy": {
            "id": 77629,
            "name": "Elder Taggawag",
            "attack": 4,
            "attackGold": 8,
            "health": 4,
            "healthGold": 8,
            "text": "<b>Start of Combat:</b> If you control 4 minions with different types, gain your minions' highest Attack and Health.",
            "textGold": "<b>Start of Combat:</b> If you control 4 minions with different types, gain double your minions' highest Attack and Health.",
        },
    },
    57892: {
        "name": "Ragnaros the Firelord",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 64424,
            "name": "BUY, INSECT!",
            "cost": 0,
            "text": "After you buy 12 cards, get Sulfuras. <i>(12 left!)</i>",
        },
        "buddy": {
            "id": 77821,
            "name": "Lucifron",
            "attack": 6,
            "attackGold": 12,
            "health": 5,
            "healthGold": 10,
            "text": "Your end of turn effects trigger an extra time.",
            "textGold": "Your end of turn effects trigger 2 extra times.",
        },
    },
    64400: {
        "name": "Rakanishu",
        "health": 30,
        "armor": 10,
        "power": {
            "id": None,
            "name": "Unknown Power",
            "cost": 0,
            "text": "TODO: Power not found in cards.json",
        },
        "buddy": {
            "id": 77823,
            "name": "Lantern Tender",
            "attack": 6,
            "attackGold": 12,
            "health": 4,
            "healthGold": 8,
            "text": "At the end of your turn, get 2 random Tavern spells that give stats.",
            "textGold": "At the end of your turn, get 4 random Tavern spells that give stats.",
        },
    },
    60212: {
        "name": "Reno Jackson",
        "health": 30,
        "armor": 16,
        "power": {
            "id": 60216,
            "name": "Gonna Be Rich!",
            "cost": 0,
            "text": "Once per game, make a friendly minion Golden.",
        },
        "buddy": {
            "id": 77825,
            "name": "Sr. Tomb Diver",
            "attack": 5,
            "attackGold": 10,
            "health": 1,
            "healthGold": 2,
            "text": "<b>Taunt</b> <b>Deathrattle:</b> Make your right-most minion Golden.",
            "textGold": "<b>Taunt</b> <b>Deathrattle:</b> Make your two right-most minions Golden.",
        },
    },
    99033: {
        "name": "Rock Master Voone",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 99034,
            "name": "Upbeat Harmony",
            "cost": 0,
            "text": "At the end of every 3 turns, get a plain copy of the left- most card in your hand. <i>(3 turns left!)</i>",
        },
        "buddy": {
            "id": 113629,
            "name": "Akali, Rock Rhino",
            "attack": 6,
            "attackGold": 12,
            "health": 6,
            "healthGold": 12,
            "text": "At the end of every 2  turns, get a plain copy of the left-most card in your hand. <i>(2 turns left!)</i>",
            "textGold": "At the end of every turn, get a plain copy of the left-most card in your hand.",
        },
    },
    70838: {
        "name": "Rokara",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 80229,
            "name": "Glory of Combat",
            "cost": 0,
            "text": "After a friendly minion kills an enemy, give it +1 Attack permanently.",
        },
        "buddy": {
            "id": 77876,
            "name": "Icesnarl the Mighty",
            "attack": 6,
            "attackGold": 12,
            "health": 2,
            "healthGold": 4,
            "text": "After a friendly minion kills an enemy, gain +3 Health permanently.",
            "textGold": "After a friendly minion kills an enemy, gain +6 Health permanently.",
        },
    },
    76562: {
        "name": "Scabbs Cutterbutter",
        "health": 30,
        "armor": 15,
        "power": {
            "id": 76563,
            "name": "I Spy",
            "cost": 2,
            "text": "<b>Discover</b> a plain copy of a minion from your next opponent's warband.",
        },
        "buddy": {
            "id": 77870,
            "name": "Warden Thelwater",
            "attack": 2,
            "attackGold": 4,
            "health": 6,
            "healthGold": 12,
            "text": "At the start of your turn, get your next opponent's Buddy.",
            "textGold": "At the start of your turn, get 2 of your next opponent's Buddy.",
        },
    },
    58027: {
        "name": "Shudderwock",
        "health": 30,
        "armor": 10,
        "power": {
            "id": 58028,
            "name": "Snicker-snack",
            "cost": 0,
            "text": "Trigger a friendly minion's <b>Battlecry</b>. <i>(Unlocks on Turn 3.)</i>",
        },
        "buddy": {
            "id": 77827,
            "name": "Muckslinger",
            "attack": 5,
            "attackGold": 10,
            "health": 5,
            "healthGold": 10,
            "text": "<b>Battlecry:</b> Get a random <b>Battlecry</b> minion.",
            "textGold": "<b>Battlecry:</b> Get 2 random <b>Battlecry</b> minions.",
        },
    },
    64480: {
        "name": "Silas Darkmoon",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 64481,
            "name": "Come One, Come All!",
            "cost": 0,
            "text": "Darkmoon Tickets are in the Tavern! Get 3 to <b>Discover</b> a minion of your Tier.",
        },
        "buddy": {
            "id": 77829,
            "name": "Burth",
            "attack": 6,
            "attackGold": 12,
            "health": 7,
            "healthGold": 14,
            "text": "After you <b>Discover</b> a minion, give it +2/+2 and improve this.",
            "textGold": "After you <b>Discover</b> a minion, give it +4/+4 and improve this.",
        },
    },
    58435: {
        "name": "Sindragosa",
        "health": 30,
        "armor": 7,
        "power": {
            "id": 57945,
            "name": "Stay Frosty",
            "cost": 0,
            "text": "Minions cost (2). The Tavern offers one fewer minion and <b><b>Freeze</b>s</b> at the end of each turn.",
        },
        "buddy": {
            "id": 77724,
            "name": "Thawed Champion",
            "attack": 4,
            "attackGold": 8,
            "health": 5,
            "healthGold": 10,
            "text": "At the end of your turn, make a random <b>Frozen</b> minion in the Tavern Golden.",
            "textGold": "At the end of your turn, make 2 random <b>Frozen</b> minions in the Tavern Golden.",
        },
    },
    60211: {
        "name": "Sir Finley Mrrgglton",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 60450,
            "name": "Adventure!",
            "cost": 0,
            "text": "At the start of the game, <b>Discover</b> a Hero Power.",
        },
        "buddy": {
            "id": 77831,
            "name": "Maxwell, Mighty Steed",
            "attack": 1,
            "attackGold": 2,
            "health": 1,
            "healthGold": 2,
            "text": "When you sell this, get the <b>Buddy</b> of your Hero Power.",
            "textGold": "When you sell this, get 2 <b>Buddies</b> of your Hero Power.",
        },
    },
    92960: {
        "name": "Sire Denathrius",
        "health": 30,
        "armor": 11,
        "power": {
            "id": 92961,
            "name": "Whodunit?",
            "cost": 0,
            "text": "At the start of the game, choose one of two <b>Quests</b>.",
        },
        "buddy": {
            "id": 101435,
            "name": "Shady Aristocrat",
            "attack": 4,
            "attackGold": 8,
            "health": 4,
            "healthGold": 8,
            "text": "When you sell this, <b>Discover</b> a <b>Quest</b>. Complete it to get an 8-Gold Coin Pouch.",
            "textGold": "When you sell this, <b>Discover</b> a <b>Quest</b>. Complete it to get a 16-Gold Coin Pouch.",
        },
    },
    62268: {
        "name": "Skycap'n Kragg",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 62269,
            "name": "Piggy Bank",
            "cost": 0,
            "text": "Gain 2 Gold. Increases by 1 each turn. <i>(Once per game.)</i>",
        },
        "buddy": {
            "id": 77833,
            "name": "Sharkbait",
            "attack": 5,
            "attackGold": 10,
            "health": 3,
            "healthGold": 6,
            "text": "When you sell this, refresh your Hero Power.",
            "textGold": "When you sell this, refresh your Hero Power.",
        },
    },
    105314: {
        "name": "Snake Eyes",
        "health": 30,
        "armor": 5,
        "power": {
            "id": 105315,
            "name": "Lucky Roll",
            "cost": 1,
            "text": "Roll a 6-sided die. Gain that much Gold. <i>(Cannot be used again for that many turns!)</i>",
        },
        "buddy": {
            "id": 113559,
            "name": "Box Cars",
            "attack": 6,
            "attackGold": 12,
            "health": 6,
            "healthGold": 12,
            "text": "At the start of your turn, roll a 6-sided die. <b>Discover</b> a  Tavern spell of that Tier.",
            "textGold": "At the start of your turn, roll two 6-sided dice. <b>Discover</b> a Tavern spell from each of those Tiers.",
        },
    },
    76521: {
        "name": "Sneed",
        "health": 30,
        "armor": 20,
        "power": {
            "id": 76520,
            "name": "Pilot the Shredder",
            "cost": 0,
            "text": "Start the game with a 2/1 Shredder that summons a minion from your hand and gives it <b>Divine Shield</b>.",
        },
        "buddy": {
            "id": 77874,
            "name": "Piloted Whirl-O-Tron",
            "attack": 6,
            "attackGold": 12,
            "health": 4,
            "healthGold": 8,
            "text": "<b>Start of Combat:</b> Copy your two left-most <b>Deathrattles</b> <i>(except other Whirl-O-Trons)</i>.",
            "textGold": "<b>Start of Combat:</b> Copy your two left-most <b>Deathrattles</b> twice <i>(except other Whirl-O-Trons)</i>.",
        },
    },
    89293: {
        "name": "Sylvanas Windrunner",
        "health": 30,
        "armor": 10,
        "power": {
            "id": 89294,
            "name": "Reclaimed Souls",
            "cost": 2,
            "text": "<b>Discover</b> a plain copy of a minion that died last combat. <i>(Unlocks on Turn 3.)</i>",
        },
        "buddy": {
            "id": 98660,
            "name": "Nathanos Blightcaller",
            "attack": 6,
            "attackGold": 12,
            "health": 7,
            "healthGold": 14,
            "text": "<b>Battlecry:</b> Sell a friendly minion. Split its stats evenly amongst its neighbors.",
            "textGold": "<b>Battlecry:</b> Sell a friendly minion. Split double its stats evenly amongst its neighbors.",
        },
    },
    105431: {
        "name": "Tae'thelan Bloodwatcher",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 105432,
            "name": "Reliquary Research",
            "cost": 0,
            "text": "Every third Tavern spell you buy costs (0). <i>(2 left!)</i>",
        },
        "buddy": {
            "id": 113650,
            "name": "Reliquary Attendant",
            "attack": 6,
            "attackGold": 12,
            "health": 4,
            "healthGold": 8,
            "text": "Once per turn, after you cast a Tavern spell, get a new copy of it.",
            "textGold": "Once per turn, after you cast a Tavern spell, get 2 new copies of it.",
        },
    },
    74646: {
        "name": "Tamsin Roame",
        "health": 30,
        "armor": 10,
        "power": {
            "id": 77911,
            "name": "Fragrant Phylactery",
            "cost": 0,
            "text": "<b>Start of Combat:</b> Give your lowest-Attack minion \"<b>Deathrattle:</b> Give your other minions this minion's stats.\"",
        },
        "buddy": {
            "id": 77878,
            "name": "Monstrosity",
            "attack": 5,
            "attackGold": 10,
            "health": 10,
            "healthGold": 20,
            "text": "After a friendly minion dies, gain its Attack.",
            "textGold": "After a friendly minion dies, gain its Attack twice.",
        },
    },
    77987: {
        "name": "Tavish Stormpike",
        "health": 30,
        "armor": 14,
        "power": {
            "id": None,
            "name": "Unknown Power",
            "cost": 0,
            "text": "TODO: Power not found in cards.json",
        },
        "buddy": {
            "id": 77880,
            "name": "Crabby",
            "attack": 2,
            "attackGold": 4,
            "health": 3,
            "healthGold": 6,
            "text": "After you remove a minion with 'Lock and Load,' get a plain copy of it.",
            "textGold": "After you remove a minion with 'Lock and Load,' get 2 plain copies of it.",
        },
    },
    98726: {
        "name": "Teron Gorefiend",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 98728,
            "name": "Rapid Reanimation",
            "cost": 0,
            "text": "Choose a friendly minion. <b>Start of Combat:</b> Destroy it. When you have space, resummon an exact copy.",
        },
        "buddy": {
            "id": 101459,
            "name": "Shadowy Construct",
            "attack": 4,
            "attackGold": 8,
            "health": 4,
            "healthGold": 8,
            "text": "Whenever a friendly minion dies, gain its maximum stats. <i>(Once per combat.)</i>",
            "textGold": "Whenever a friendly minion dies, gain its maximum stats. <i>(Twice per combat.)</i>",
        },
    },
    60367: {
        "name": "Tess Greymane",
        "health": 30,
        "armor": 17,
        "power": {
            "id": 63162,
            "name": "Bob's Burgles",
            "cost": 1,
            "text": "<b>Refresh</b> the Tavern with plain copies of your last  opponent's warband.",
        },
        "buddy": {
            "id": 77835,
            "name": "Hunter of Old",
            "attack": 5,
            "attackGold": 10,
            "health": 3,
            "healthGold": 6,
            "text": "At the start of your turn, get your last opponent's <b>Buddy</b>.",
            "textGold": "At the start of your turn, get 2 of your last opponent's <b>Buddy</b>.",
        },
    },
    59203: {
        "name": "The Curator",
        "health": 30,
        "armor": 16,
        "power": {
            "id": 59201,
            "name": "Menagerist",
            "cost": 0,
            "text": "Start the game with a 2/2 Amalgam with <b>Venomous</b> and all minion types.",
        },
        "buddy": {
            "id": 77837,
            "name": "Mishmash",
            "attack": 4,
            "attackGold": 8,
            "health": 4,
            "healthGold": 8,
            "text": "Whenever your Amalgam gains stats, this gains them too.",
            "textGold": "Whenever your Amalgam gains stats, this gains them twice.",
        },
    },
    58021: {
        "name": "The Great Akazamzarak",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 58022,
            "name": "Prestidigitation",
            "cost": 0,
            "text": "Choose a <b>Secret</b>. Put it into the battlefield.",
        },
        "buddy": {
            "id": 77839,
            "name": "Street Magician",
            "attack": 3,
            "attackGold": 6,
            "health": 5,
            "healthGold": 10,
            "text": "'Prestidigitation' chooses from Better <b>Secrets</b>.",
            "textGold": "'Prestidigitation' chooses from Better <b>Secrets</b> twice.",
        },
    },
    97186: {
        "name": "The Jailer",
        "health": 30,
        "armor": 10,
        "power": {
            "id": 122959,
            "name": "Rune of Damnation",
            "cost": 1,
            "text": "Destroy a friendly Undead to get a random Undead. <i>(Unlocks at Tier 2.)</i>",
        },
        "buddy": {
            "id": 98690,
            "name": "Mawsworn Soulkeeper",
            "attack": 2,
            "attackGold": 4,
            "health": 2,
            "healthGold": 4,
            "text": "<b>Deathrattle:</b> Summon 2 random Undead.",
            "textGold": "<b>Deathrattle:</b> Summon 4 random Undead.",
        },
    },
    58024: {
        "name": "The Lich King",
        "health": 30,
        "armor": 14,
        "power": {
            "id": 58040,
            "name": "Reborn Rites",
            "cost": 0,
            "text": "Give a minion <b>Reborn</b> until next turn.",
        },
        "buddy": {
            "id": 77841,
            "name": "Arfus",
            "attack": 8,
            "attackGold": 16,
            "health": 4,
            "healthGold": 8,
            "text": "After a friendly minion is <b>Reborn</b>, give it this minion's Attack.",
            "textGold": "After a friendly minion is <b>Reborn</b>, give it this minion's Attack twice.",
        },
    },
    104567: {
        "name": "The Nameless One",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 104569,
            "name": "BGDUO_HERO_100p",
            "cost": 0,
            "text": "<b>Start of Game:</b> Copy your teammate's Hero Power.",
        },
        "buddy": {
            "id": 113633,
            "name": "Faceless One",
            "attack": 1,
            "attackGold": 2,
            "health": 1,
            "healthGold": 2,
            "text": "When you sell this, get the <b>Buddy</b> of your teammate's Hero Power.",
            "textGold": "When you sell this, get 2 <b>Buddies</b> of your teammate's Hero Power.",
        },
    },
    57893: {
        "name": "The Rat King",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 63127,
            "name": "A Tale of Kings",
            "cost": 2,
            "text": "<b>Discover</b> a minion of a specific minion type. Swaps type each turn.",
        },
        "buddy": {
            "id": 77843,
            "name": "Pigeon Lord",
            "attack": 3,
            "attackGold": 6,
            "health": 4,
            "healthGold": 8,
            "text": "Your <b>Refreshes</b> are free while the Tavern doesn't have the minion type of your Hero Power.",
            "textGold": "Your <b>Refreshes</b> are free while the Tavern doesn't have the minion type of your Hero Power.",
        },
    },
    103477: {
        "name": "Thorim, Stormlord",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 104628,
            "name": "Choose Your Champion",
            "cost": 0,
            "text": "<b><b>Passive</b>.</b> At the start of the game, <b>Discover</b> a Tier 7 minion to get after you spend 60 Gold. <i>(60 left!)</i>",
        },
        "buddy": {
            "id": 113557,
            "name": "Veranus, Stormlord's Mount",
            "attack": 5,
            "attackGold": 10,
            "health": 2,
            "healthGold": 4,
            "text": "At the end of your turn, transform the minion to the left of this into one from a Tier higher <i>(up to Tier 7!)</i>",
            "textGold": "At the end of your turn, transform the minion to the left of this into one from two Tiers higher <i>(up to Tier 7!)</i>",
        },
    },
    67356: {
        "name": "Tickatus",
        "health": 30,
        "armor": 17,
        "power": {
            "id": 67357,
            "name": "Prize Wall",
            "cost": 0,
            "text": "Every 4 turns, <b>Discover</b> a Darkmoon Prize. <i>(3 turns left!)</i>",
        },
        "buddy": {
            "id": 77845,
            "name": "Ticket Collector",
            "attack": 6,
            "attackGold": 12,
            "health": 6,
            "healthGold": 12,
            "text": "When you sell this, <b>Discover</b> a Darkmoon Prize from the next Tier.",
            "textGold": "When you sell this, <b>Discover</b> 2 Darkmoon Prizes from the next Tier.",
        },
    },
    126537: {
        "name": "Time Twister Chromie",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 126538,
            "name": "Mana Per Minute",
            "cost": 0,
            "text": "<b>Refresh</b> the Tavern with Tavern spells.",
        },
    },
    57891: {
        "name": "Trade Prince Gallywix",
        "health": 30,
        "armor": 5,
        "power": {
            "id": 57559,
            "name": "Smart Savings",
            "cost": 1,
            "text": "After you sell a minion, gain 1 Gold next turn.",
        },
        "buddy": {
            "id": 77847,
            "name": "Bilgewater Mogul",
            "attack": 6,
            "attackGold": 12,
            "health": 5,
            "healthGold": 10,
            "text": "At the end of your turn, increase your maximum Gold by 1.",
            "textGold": "At the end of your turn, increase your maximum Gold by 2.",
        },
    },
    132578: {
        "name": "Tras'tath, Soul Parasite",
        "health": 30,
        "armor": 10,
        "power": {
            "id": 132581,
            "name": "Void Power",
            "cost": 0,
            "text": "At the start of the game, <b>Discover</b> a Tier 5 minion with a <b>Dark Gift</b>. It unlocks on Turn 7. <i>(6 turns left!)</i>",
        },
    },
    80247: {
        "name": "Vanndar Stormpike",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 80248,
            "name": "Stormpike Strength",
            "cost": 0,
            "text": "When you have space in combat, summon a copy of your highest-Health minion. <i>(Unlocks on Turn 7.)</i>",
        },
        "buddy": {
            "id": 77886,
            "name": "Stormpike Lieutenant",
            "attack": 4,
            "attackGold": 8,
            "health": 7,
            "healthGold": 14,
            "text": "At the end of your turn, give your right-most minion +10 Health.",
            "textGold": "At the end of your turn, give your right-most minion +20 Health.",
        },
    },
    79615: {
        "name": "Varden Dawngrasp",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 80539,
            "name": "Twice as Nice",
            "cost": 0,
            "text": "After the Tavern is <b>Refreshed</b>, copy its highest-Tier minion and <b>Freeze</b> them both.",
        },
        "buddy": {
            "id": 77888,
            "name": "Varden's Aquarrior",
            "attack": 3,
            "attackGold": 6,
            "health": 6,
            "healthGold": 12,
            "text": "'Twice as Nice' also gives both minions stats equal to your Tier.",
            "textGold": "'Twice as Nice' also gives both minions stats equal to your Tier twice.",
        },
    },
    71463: {
        "name": "Vol'jin",
        "health": 30,
        "armor": 17,
        "power": {
            "id": 71464,
            "name": "Spirit Swap",
            "cost": 0,
            "text": "Choose 2 minions. They gain each other's Attack until next turn.",
        },
        "buddy": {
            "id": 77849,
            "name": "Master Gadrin",
            "attack": 7,
            "attackGold": 14,
            "health": 6,
            "healthGold": 12,
            "text": "<b>Start of Combat:</b> Give the minion to the left of this Health equal to its Attack.",
            "textGold": "<b>Start of Combat:</b> Give adjacent minions Health equal to their Attack.",
        },
    },
    70956: {
        "name": "Xyrella",
        "health": 30,
        "armor": 12,
        "power": {
            "id": 70957,
            "name": "See the Light",
            "cost": 2,
            "text": "Choose a minion in the Tavern. Set its stats to 2 and add it to your hand.",
        },
        "buddy": {
            "id": 77851,
            "name": "Baby Elekk",
            "attack": 4,
            "attackGold": 8,
            "health": 4,
            "healthGold": 8,
            "text": "Whenever you play a minion with less Attack than this, give it +1/+1 and improve this.",
            "textGold": "Whenever you play a minion with less Attack than this, give it +2/+2 and improve this.",
        },
    },
    66196: {
        "name": "Y'Shaarj",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 66197,
            "name": "Embrace Your Rage",
            "cost": 2,
            "text": "<b>Start of Combat: </b>Summon and get a minion of your Tier.",
        },
        "buddy": {
            "id": 77857,
            "name": "Baby Y'Shaarj",
            "attack": 6,
            "attackGold": 12,
            "health": 6,
            "healthGold": 12,
            "text": "After you summon a minion of your Tier, give your minions +1/+1.",
            "textGold": "After you summon a minion of your Tier, give your minions +2/+2.",
        },
    },
    59805: {
        "name": "Yogg-Saron, Hope's End",
        "health": 30,
        "armor": 10,
        "power": {
            "id": 122958,
            "name": "Puzzle Box",
            "cost": 0,
            "text": "At the start of your turn, cast a random Tavern spell. <i>(Unlocks on Turn 3.)</i>",
        },
    },
    60370: {
        "name": "Ysera",
        "health": 30,
        "armor": 17,
        "power": {
            "id": 61408,
            "name": "Dream Portal",
            "cost": 0,
            "text": "The Tavern offers an extra Dragon whenever it is <b>Refreshed</b>.",
        },
        "buddy": {
            "id": 77855,
            "name": "Valithria Dreamwalker",
            "attack": 6,
            "attackGold": 12,
            "health": 4,
            "healthGold": 8,
            "text": "Whenever a Dragon enters your warband or the Tavern, gain +1/+1.",
            "textGold": "Whenever a Dragon enters your warband or the Tavern, gain +2/+2.",
        },
    },
    64485: {
        "name": "Zephrys, the Great",
        "health": 30,
        "armor": 17,
        "power": {
            "id": 64486,
            "name": "Three Wishes",
            "cost": 3,
            "text": "If you have two copies of a minion, find the third. <i>(3 Wishes left!)</i>",
        },
        "buddy": {
            "id": 77859,
            "name": "Phyresz",
            "attack": 4,
            "attackGold": 8,
            "health": 4,
            "healthGold": 8,
            "text": "When you sell this, <b>Discover</b> a plain copy of a different minion that you have exactly one of.",
            "textGold": "When you sell this, <b>Discover</b> a plain copy of a different minion that you have exactly one of twice.",
        },
    },
    117409: {
        "name": "Zerek, Master Cloner",
        "health": 30,
        "armor": 18,
        "power": {
            "id": 117410,
            "name": "Cloning Gallery",
            "cost": 0,
            "text": "Once per game, summon an exact copy of a friendly minion.",
        },
        "buddy": {
            "id": 122327,
            "name": "Mini-Zerek",
            "attack": 1,
            "attackGold": 2,
            "health": 1,
            "healthGold": 2,
            "text": "<b>Battlecry:</b> Choose a minion in the Tavern. Transform into a copy of it. ",
            "textGold": "<b>Battlecry:</b> Choose a minion in the Tavern. Transform into a Golden copy of it.",
        },
    },
}
